### ISSUE TITLE
Redundant model materialization in models

### ISSUE THREAD

**Issue by sp35** [HousewareHQ/dbt_intercom_metrics#4]
https://github.com/HousewareHQ/dbt_intercom_metrics/blob/6cc2ae6f78bdda309e903c5ff8bc008ac9eefa37/dbt_project.yml#L8-L10

Since there's default materialization for each model, it makes sense to remove default materialization config in individual models.
https://github.com/HousewareHQ/dbt_intercom_metrics/blob/6cc2ae6f78bdda309e903c5ff8bc008ac9eefa37/models/metrics/intercom__monthly_average_ticket_volume.sql#L6

**Comment by AryanMadhavVerma** [comment]
I think it's okay to have explicit declaration in each model. @shubh24 ?
