### ISSUE TITLE
Inconsistent casing of columns

### ISSUE THREAD

**Issue by sp35** [HousewareHQ/dbt_intercom_metrics#5]
Since this package is supposed to be warehouse-agnostic, we should keep our column names as lowercased. Unquoted column names are uppercased by Snowflake, so it should work.

https://github.com/HousewareHQ/dbt_intercom_metrics/blob/6cc2ae6f78bdda309e903c5ff8bc008ac9eefa37/models/metrics/metrics.yml#L21

**Comment by AryanMadhavVerma** [comment]
Fixed. Raised a PR for the same. @sp35 @shubh24
