### ISSUE TITLE
Metrics' permalinks not updated in readme

### ISSUE THREAD

**Issue by sp35** [HousewareHQ/dbt_intercom_metrics#6]
Metric permalinks in readme are not pointing to the metric yaml configuration in https://github.com/HousewareHQ/dbt_intercom_metrics/blob/main/models/metrics/metrics.yml

PS: metric names do not match with name in yaml (`__`)

**Comment by AryanMadhavVerma** [comment]
Removed #line redirection completely. Creates inconsistency when code is updated.
